version: '3.7'

services:
    frontend:
        image: "node:lts"
        environment:
            BROWSER: none
            PORT: 3000
        network_mode: "host"
        volumes:
            - ./workspace/client:/client
        working_dir: /client
        user: node
        command: bash -c "npm install && npm run start"
    backend:
        image: "node:lts"
        depends_on:
            - db
        environment:
            PORT: 3001
            DATABASE_URL: postgres://hatchways:password123@localhost:5432/messenger
            SESSION_SECRET: nyancat
        network_mode: "host"
        volumes:
            - ./workspace/server:/server
        working_dir: /server
        user: node
        command: bash -c "npm install && npm run seed && npm run dev"
    db:
        image: "postgres:12"
        restart: unless-stopped
        environment:
            POSTGRES_USER: hatchways
            POSTGRES_PASSWORD: password123
            POSTGRES_DB: messenger
        ports:
            - 5432:5432

